source 'https://rubygems.org'

gem 'json'
gem 'rake'
gem 'haml'
gem 'slim'
gem 'sequel'
gem 'rspec', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'
gem 'padrino', '0.12.4'
gem 'sass', '~> 3.4.11'
gem 'pg'